"""Add last_active_at to User

Revision ID: 0eb1e4f28bb9
Revises: 544389102861
Create Date: 2025-10-19 23:01:38.266874

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0eb1e4f28bb9'
down_revision = '544389102861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_active_at')
    # ### end Alembic commands ###
