"""Add default_weave_id to User

Revision ID: 0fdeee3ae7d9
Revises: ddecb8cd9caf
Create Date: 2025-10-19 20:44:55.021118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0fdeee3ae7d9'
down_revision = 'ddecb8cd9caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_weave_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_weave_id')
    # ### end Alembic commands ###
