"""Add last_accessed_weave_id to User

Revision ID: 544389102861
Revises: 0fdeee3ae7d9
Create Date: 2025-10-19 21:06:24.906839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '544389102861'
down_revision = '0fdeee3ae7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove default_weave_id column (no longer needed)
    op.drop_column('user', 'default_weave_id')
    # Add last_accessed_weave_id column instead
    op.add_column('user', sa.Column('last_accessed_weave_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_accessed_weave_id')
    op.add_column('user', sa.Column('default_weave_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###
