"""remove icon color description from entry_type

Revision ID: ddecb8cd9caf
Revises: 003_remove_plural_name
Create Date: 2025-10-17 22:52:26.650809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ddecb8cd9caf'
down_revision = '003_remove_plural_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entry_type_parent_id'), 'entry_type', ['parent_id'], unique=False)
    op.drop_constraint(op.f('fk_entry_type_parent_id'), 'entry_type', type_='foreignkey')
    op.create_foreign_key(None, 'entry_type', 'entry_type', ['parent_id'], ['id'])
    op.drop_column('entry_type', 'color')
    op.drop_column('entry_type', 'icon')
    op.drop_column('entry_type', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_type', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry_type', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('entry_type', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entry_type', type_='foreignkey')
    op.create_foreign_key(op.f('fk_entry_type_parent_id'), 'entry_type', 'entry_type', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_entry_type_parent_id'), table_name='entry_type')
    # ### end Alembic commands ###
